### ISSUE TITLE
control_structure_iter ignores blocks when iterating jump_offsets

### ISSUE THREAD

**Issue by x0ret** [rocky/python-control-flow#1]
> I tried looking to see how python-control-flow handles this. It creates the control-flow graph and dominators correctly, but it comes up with the wrong control flow. I will look at how to fix that over the weekend. I will also create a new decompile project for just 3.7 stripped down from uncompyle6.

According to what you said, I checked the code and here is the result:

I found three issues in the `structured_cf.py`:

1. due to this [condition](https://github.com/rocky/python-control-flow/blob/master/control_flow/structured_cf.py#L355) one of the blocks (block#10 in my case) is ignored, precisely `jump_block in dominator_blocks` is `False` So we don't have `ELSE` for that.

I'm not sure this fix is correct or not but suppose we patch the condition to:

```python
if jump_block not in cfg.seen_blocks:
```

2. fixing previous issue still is not enough, since [this condition](https://github.com/rocky/python-control-flow/blob/master/control_flow/structured_cf.py#L361) prevent from handling else cases and the reason is that sometimes (specially in 3.7+) we may have two conditions (chained comparison) so `len(...) == 2` and we can have following fix:

```python 
if len(jump_block.predecessors) in (1, 2):
```  

3. Finally it seems we have correct control flow however there is still an issue, please consider following control flow:

```
ELSE
  5:     >>   18 LOAD_CONST                3 (11)
              20 LOAD_GLOBAL               0 (a)
              22 DUP_TOP
              24 ROT_THREE
              26 COMPARE_OP                1 (<=)
              28 POP_JUMP_IF_FALSE        38 (to 38)
              30 LOAD_CONST                4 (15)
              32 COMPARE_OP                1 (<=)
IF
              34 POP_JUMP_IF_FALSE        70 (to 70)
THEN
              36 JUMP_FORWARD              4 (to 42)
         >>   38 POP_TOP
              40 JUMP_FORWARD             28 (to 70)
END_ELSE
END_IF
LOOP
  6:     >>   42 SETUP_LOOP               34 (to 78)
              44 LOAD_GLOBAL               2 (range)
```

It's obvious that `END_ELSE` is not correct in this case and should be shifted to nearly end of instrs. The issue however is one of the blocks (block#5 in my case) is placed at the end of parent block so [`cs_tree_to_str#L497`](https://github.com/rocky/python-control-flow/blob/master/control_flow/structured_cf.py#L497) uses that as end of else block and results as i described. following block:
```
              36 JUMP_FORWARD              4 (to 42)
         >>   38 POP_TOP
              40 JUMP_FORWARD             28 (to 70)
```

it needs more work for me to find the issue.  

Please note i used this test case:

```python
if a == 10:
    print(0)
else:
    if 11 <= a <= 15:
        for i in range(10):
            print(i)
    else:
        print(3)
```

**Comment by rocky** [comment]
Thanks for looking at this. I won't have time right now to do anything here, I hope you will though. 

The most fundamental thing is that the control flow graph is correct and that the dominator tree is correct. The right way to figure out where the end of an "if" block is to use reverse dominators (which isn't there, but only in approximation). The largest reach of the the join is tells you what block this is a closer for. If it happens to be an "If" then that' is the end of the if block. But yes, not that we separate "if" into a "then" block and an "else" block. But maybe there should be an separate "if" block which contains the test and enclosing "then" and (optional) "else" block(s).

**Comment by rocky** [comment]
The code has moved quite a bit from this. We no longer try to detect Python control flow but instead rather the nesting and sequencing structure which can be used by a context-free parser.
